version: "3.9"
services:
  frontend:
    build: FRONTEND/.
    image: ghcr.io/codebattles-nn/frontend
    ports:
      - "8001:80"
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  frontend-v2:
    build: FRONTEND_V2/.
    image: ghcr.io/codebattles-nn/frontend-v2
    ports:
      - "8002:80"
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  backend:
    build: BACKEND/.
    image: ghcr.io/codebattles-nn/backend
    environment:
      CHECKER_PORT: 7070
      DB_HOST: postgres
      DB_USERNAME: "postgres"
      DB_PASSWORD: "admin"
      DB_NAME: "cb"
      HASH_SALT: 4a5ecb2c236d1c4c3e670fcc76b8d1566c94d096bcf5f700511bb039507ad518
      REDIS_HOST: redis
      ADMIN_LOGIN: adminnn23
      ADMIN_PASSWORD: goodprog
      PYTHONUNBUFFERED: TRUE
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet


  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "cb"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "admin"
      REQUIRE_CAPTCHA: false

    ports:
      - "25565:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cb" ]
      interval: 2s
      timeout: 2s
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  gateway:
    build: GATEWAY/.
    image: ghcr.io/codebattles-nn/gateway
    ports:
      - "2500:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  init_configurer:
    build: INIT_CONFIGURER/.
    image: ghcr.io/codebattles-nn/init-configurer
    environment:
      DB_HOST: postgres
      DB_USERNAME: "postgres"
      DB_PASSWORD: "admin"
      DB_NAME: "cb"
    links:
      - backend
      - postgres
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  checker-java:
    build:
      dockerfile: z_checkers_dockerfiles/Java.Dockerfile
    image: ghcr.io/codebattles-nn/checker-java
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  checker-python:
    build:
      dockerfile: z_checkers_dockerfiles/Python.Dockerfile
    image: ghcr.io/codebattles-nn/checker-python
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

#  checker-cpp:
#    build:
#      dockerfile: ./CPP.Dockerfile
#    image: ghcr.io/codebattles-nn/checker-cpp
#    restart: unless-stopped
#  checker-pascal:
#    build:
#      dockerfile: ./Pascal.Dockerfile
#    image: ghcr.io/codebattles-nn/checker-pascal
#    restart: unless-stopped

networks:
  no-internet:
    driver: bridge
    internal: true
  with-internet:
    driver: bridge


