version: "3.9"
services:
  frontend-v2:
    build: FRONTEND_V2/.
    image: ghcr.io/codebattles-nn/frontend-v2
    ports:
      - "8002:80"
    restart: unless-stopped
    environment:
      VITE_ENV: "production"

    networks:
      - with-internet
      - no-internet

  backend:
    build: BACKEND_V2/.
    image: ghcr.io/codebattles-nn/backend-v2
    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "cb"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "admin"
      REQUIRE_CAPTCHA: false

    ports:
      - "25565:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cb" ]
      interval: 2s
      timeout: 2s
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  gateway:
    build: GATEWAY/.
    image: ghcr.io/codebattles-nn/gateway
    ports:
      - "2500:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  checker-java:
    build:
      dockerfile: z_checkers_dockerfiles/Java.Dockerfile
    image: ghcr.io/codebattles-nn/checker-java
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

  checker-python:
    build:
      dockerfile: z_checkers_dockerfiles/Python.Dockerfile
    image: ghcr.io/codebattles-nn/checker-python
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet

#  checker-cpp:
#    build:
#      dockerfile: ./CPP.Dockerfile
#    image: ghcr.io/codebattles-nn/checker-cpp
#    restart: unless-stopped
#  checker-pascal:
#    build:
#      dockerfile: ./Pascal.Dockerfile
#    image: ghcr.io/codebattles-nn/checker-pascal
#    restart: unless-stopped

networks:
  no-internet:
    driver: bridge
    internal: true
  with-internet:
    driver: bridge


