version: "3.9"
services:
  web:
    build: .
    environment:
      CHECKER_PORT: 7070
      DB_HOST: postgres
      DB_USERNAME: "postgres"
      DB_PASSWORD: "admin"
      DB_NAME: "cb"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "cb"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "25565:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cb" ]
      interval: 2s
      timeout: 2s
  checker-java:
    build: PROGRAM_CHECK_SYSTEM/.
    environment:
      SERVER_ENDPOINT: http://web:5000/api/check_system_callback
      ENV_EXECUTOR_ENABLE: true
  checker-python:
    build: PROGRAM_CHECK_SYSTEM/.
    environment:
      SERVER_ENDPOINT: http://web:5000/api/check_system_callback
      ENV_EXECUTOR_ENABLE: true
      ENV_EXECUTOR_RUN_COMMAND: python3
      ENV_EXECUTOR_FILENAME: main.py

