version: "3.9"
services:
  frontend:
    build: FRONTEND/.
    ports:
      - "8001:80"
    restart: unless-stopped
    networks:
      - no-internet
  frontend-v2:
    build: FRONTEND_V2/.
    ports:
      - "8002:80"
    restart: unless-stopped
    networks:
      - no-internet
  backend:
    build: BACKEND/.
    environment:
      CHECKER_PORT: 7070
      DB_HOST: postgres
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: "cb"
      HASH_SALT: ${HASH_SALT}
      REDIS_HOST: redis
      PYTHONUNBUFFERED: TRUE
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REQUIRE_CAPTCHA: true
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    restart: unless-stopped
    networks:
      - no-internet

  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - no-internet
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "cb"
      POSTGRES_USER: ${DATABASE_USER}
      PGUSER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "25565:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cb" ]
      interval: 2s
      timeout: 2s
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet
  gateway:
    build: GATEWAY/.
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - with-internet
      - no-internet
  init_configurer:
    build: INIT_CONFIGURER/.
    environment:
      DB_HOST: postgres
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: "cb"
    links:
      - backend
      - postgres
    restart: unless-stopped
    networks:
      - no-internet
  checker-java:
    build:
      dockerfile: z_checkers_dockerfiles/Java.Dockerfile
    restart: unless-stopped
    networks:
      - no-internet
  checker-python:
    build:
      dockerfile: z_checkers_dockerfiles/Python.Dockerfile
    restart: unless-stopped
    networks:
      - no-internet
#  checker-cpp:
#    build:
#      dockerfile: ./CPP.Dockerfile
#    restart: unless-stopped
#  checker-pascal:
#    build:
#      dockerfile: ./Pascal.Dockerfile
#    restart: unless-stopped


networks:
  no-internet:
    driver: bridge
    internal: true
  with-internet:
    driver: bridge


