CREATE TABLE answer
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    competition_id           BIGINT,
    user_id                  BIGINT,
    status                   VARCHAR(255),
    score                    INTEGER,
    code                     VARCHAR(255),
    checker_id               BIGINT,
    result                   VARCHAR(255),
    competitions_problems_id BIGINT,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

CREATE TABLE checker
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    display_name            VARCHAR(255),
    language_highlight_name VARCHAR(255),
    address                 VARCHAR(255),
    CONSTRAINT pk_checker PRIMARY KEY (id)
);

CREATE TABLE competitions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    organizer_id BIGINT,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000)                           NOT NULL,
    started_at   TIMESTAMP WITHOUT TIME ZONE,
    ended_at     TIMESTAMP WITHOUT TIME ZONE,
    show_rating  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_competitions PRIMARY KEY (id)
);

CREATE TABLE competitions_checkers
(
    competition_id BIGINT NOT NULL,
    checkers_id    BIGINT NOT NULL,
    CONSTRAINT pk_competitions_checkers PRIMARY KEY (competition_id, checkers_id)
);

CREATE TABLE competitions_members
(
    competition_id BIGINT NOT NULL,
    members_id     BIGINT NOT NULL,
    CONSTRAINT pk_competitions_members PRIMARY KEY (competition_id, members_id)
);

CREATE TABLE competitions_problems
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    priority       INTEGER                                 NOT NULL,
    slug           VARCHAR(255),
    competition_id BIGINT,
    problem_id     BIGINT,
    CONSTRAINT pk_competitionsproblems PRIMARY KEY (id)
);

CREATE TABLE problem
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description TEXT,
    in_data     TEXT,
    out_data    TEXT,
    tests       TEXT,
    examples    TEXT,
    CONSTRAINT pk_problem PRIMARY KEY (id)
);

CREATE TABLE users_
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    password   VARCHAR(255),
    name       VARCHAR(255),
    roles      VARCHAR(255),
    CONSTRAINT pk_users_ PRIMARY KEY (id)
);

CREATE TABLE variables
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    value VARCHAR(255),
    CONSTRAINT pk_variables PRIMARY KEY (id)
);

ALTER TABLE variables
    ADD CONSTRAINT uc_variables_name UNIQUE (name);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_CHECKER FOREIGN KEY (checker_id) REFERENCES checker (id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_COMPETITIONSPROBLEMS FOREIGN KEY (competitions_problems_id) REFERENCES competitions_problems (id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_USER FOREIGN KEY (user_id) REFERENCES users_ (id);

ALTER TABLE competitions_problems
    ADD CONSTRAINT FK_COMPETITIONSPROBLEMS_ON_COMPETITION FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE competitions_problems
    ADD CONSTRAINT FK_COMPETITIONSPROBLEMS_ON_PROBLEM FOREIGN KEY (problem_id) REFERENCES problem (id);

ALTER TABLE competitions
    ADD CONSTRAINT FK_COMPETITIONS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES users_ (id);

ALTER TABLE competitions_checkers
    ADD CONSTRAINT fk_comche_on_checker FOREIGN KEY (checkers_id) REFERENCES checker (id);

ALTER TABLE competitions_checkers
    ADD CONSTRAINT fk_comche_on_competition FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE competitions_members
    ADD CONSTRAINT fk_commem_on_competition FOREIGN KEY (competition_id) REFERENCES competitions (id);

ALTER TABLE competitions_members
    ADD CONSTRAINT fk_commem_on_user FOREIGN KEY (members_id) REFERENCES users_ (id);