CREATE TABLE posts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    title        VARCHAR(255)                            NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    show_at_main BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);