name: Pull Request Tests
on: 
  pull_request_target:
    branches:
      - master

jobs:
    build:
        name: Docker build test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        - name: build
          run: docker compose -p test_codebattles build
