name: Pull Request Tests
on: 
  pull_request_target:
    branches:
      - master

jobs:
    build:
        name: Docker build test
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - name: build
          run: docker compose -p test_codebattles build
