name: Code tests
on: [workflow_dispatch]

jobs:
    build:
        name: build
        runs-on: self-hosted
        steps:
        - name: Docker up
          run: docker compose -p test_codebattles -f test-docker-compose.yml up  -d
        - name: Sleep for 30 seconds
          uses: jakejarvis/wait-action@master
          with:
            time: '30s'
        - uses: matt-ball/newman-action@master
          with:
            collection: tests/autotests.json
            environment: tests/local_env.json
        - name: Docker down
          if: always()
          run: docker compose -p test_codebattles -f test-docker-compose.yml down
          
