name: newman-tests
on: 
  pull_request:
    branches:
      - master

jobs:
    build:
        name: build
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v1
        - name: Docker up
          run: docker compose -p test_codebattles -f test-docker-compose.yml up  -d
        - uses: matt-ball/newman-action@master
          with:
            collection: tests/autotests.json
            environment: tests/local_env.json
        - name: Docker down
          run: docker compose -p test_codebattles -f test-docker-compose.yml down
          
