name: Push Docker Images to latest

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: codebattles.cr.cloud.ru
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Pull images
        run: docker compose pull

      - name: Build images
        run: docker compose build

      - name: Push images
        run: docker compose push
