name: Github Registry push

on: [workflow_dispatch]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  push:
    runs-on: ubuntu-latest
    needs: [login]
    steps:
      - name: Docker compose build
        run: docker compose build
        
      - name: Docker compose push
        run: docker compose push
      
